
### Entic api
### Use VSCode HTTP Client pluggin to call those requests

### Variables

### search "Google"

@searchTerm = Google

https://api.enthic.fr/company/search/page?page=1&per_page=30&probe={{searchTerm}}

### get APE

https://api.enthic.fr/company/ape

### get company data by Siren

@siren = 443061841
https://api.enthic.fr/company/siren/{{siren}}
